Updating R CMD check Actions
poissonconsulting/hsi pull request #6
Opened 2021-11-10 19:12 UTC by MowahidLatif

Please wait for confirmation to merge. Waiting for proper result of checks.

2021-11-10 19:35 UTC, MowahidLatif commented
Please merge this branch. Everything is in order.

2021-11-11 23:08 UTC, aylapear requested changes
can you put the badges all together, you will find the rest around line 22. move the R-CMD-check down to them and put the badge start and end syntax around the whole group.

2021-11-12 20:22 UTC, MowahidLatif commented
Please merge this branch. Everything is in order.

2021-11-12 23:07 UTC, aylapear approved these changes

2021-11-12 23:07 UTC, merged